java_library(
  name = "asm-3.1",
  srcs = [
    "agent/asm-3.1.jar",
    "agent/asm-commons-3.1.jar",
  ],
)

java_library(
  name = "google-collect-1.0",
  srcs = [
    "agent/google-collect-1.0.jar",
  ],
)

